os: Visual Studio 2017

version: 1.1.3-alpha-{build}

nuget:
  project_feed: true

install:
 - cmd: nuget sources add -Name makingsense-aspnet -Source https://ci.appveyor.com/nuget/makingsense-aspnet -UserName dtru+read@makingsense.com -Password 4@pdw@BlfpQn

before_build:
 - cmd: set DOTNET_ASSEMBLY_FILE_VERSION=%APPVEYOR_BUILD_NUMBER%
 - cmd: set DOTNET_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
 - ps: dotnet restore

artifacts:
 - path: '**\*.nupkg'

build_script:
 - cmd: dotnet build src/MakingSense.AspNetCore.Authentication.SimpleToken --version-suffix %APPVEYOR_BUILD_NUMBER%

after_build:
 - cmd: dotnet pack src/MakingSense.AspNetCore.Authentication.SimpleToken --version-suffix %APPVEYOR_BUILD_NUMBER%

notifications:
 - provider: Slack
   auth_token:
     secure: fOssPHTsqm6seWcnywN2TJE9gLtRdd1iXLRWWWWAhx4atR0u0ECGb/9Ij/gI/zafJI+FQvevEemi9epjeRhV/g==
   channel: rest-api
   template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_"
